### ISSUE TITLE
utiliser une librairie pour le client SOAP

### ISSUE THREAD

**Issue by pknoth** [sgmap/api-caf#3]
Actuellement, les requêtes au service de la cnaf sont réalisés via une requête brute créant l'enveloppe SOAP en chaine de caractères.

Trouver et utiliser une librairie réalisant les requêtes SOAP

**Comment by jdesboeufs** [comment]
Quel intérêt ?

**Comment by jdesboeufs** [comment]
On avait une lib pour la première implémentation qu'on avait faite.
1) On utilisait 1% de la lib.
2) Le service en face n'est pas conforme, donc il faut tordre de partout.

**Comment by pknoth** [comment]
OK on reste sur la solution éxistante
